//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBalance
    {
        public int fId_Balance { get; set; }
        public int fId_Role { get; set; }
        public int fId_Bank { get; set; }
        public string fCreditCard_Balance { get; set; }
        public string fStatus_Balance { get; set; }
        public string fToken_Balance { get; set; }
        public Nullable<System.DateTime> fPayTime_Balance { get; set; }
        public Nullable<System.DateTime> fVerify_Balance { get; set; }
        public string fRemark_Balance { get; set; }
    
        public virtual tBank tBank { get; set; }
        public virtual tRole tRole { get; set; }
    }
}
