//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tBank()
        {
            this.tBalances = new HashSet<tBalance>();
        }
    
        public int fId_Bank { get; set; }
        public int fId_Role { get; set; }
        public string fBank_Bank { get; set; }
        public string fName_Bank { get; set; }
        public string fAccount_Bank { get; set; }
        public string fNumber_Bank { get; set; }
        public Nullable<System.DateTime> fValidate_Bank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBalance> tBalances { get; set; }
        public virtual tRole tRole { get; set; }
    }
}
