//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFollow
    {
        public int fId_Follow { get; set; }
        public int fId_Self_Role { get; set; }
        public int fId_Target_Role { get; set; }
    
        public virtual tRole tRole { get; set; }
        public virtual tRole tRole1 { get; set; }
    }
}
