//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGame()
        {
            this.tGameGroups = new HashSet<tGameGroup>();
            this.tGameQAs = new HashSet<tGameQA>();
            this.tGameSteps = new HashSet<tGameStep>();
        }
    
        public int fId_Game { get; set; }
        public string fId_Location { get; set; }
        public Nullable<int> fType_Game { get; set; }
        public string fName_Game { get; set; }
        public Nullable<int> fOrder_Game { get; set; }
    
        public virtual tLocation tLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameGroup> tGameGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameQA> tGameQAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameStep> tGameSteps { get; set; }
    }
}
