//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGameGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGameGroup()
        {
            this.tGames = new HashSet<tGame>();
            this.tGameUnlocks = new HashSet<tGameUnlock>();
            this.tGameRecords = new HashSet<tGameRecord>();
        }
    
        public int fId_GameGroup { get; set; }
        public string fName_GameGroup { get; set; }
        public string fGameLV_GameGroup { get; set; }
        public string fDescript_GameGroup { get; set; }
        public int fId_Role { get; set; }
        public string fPhoto_GameGroup { get; set; }
        public string fId_Route { get; set; }
        public Nullable<int> fCost_GameGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGame> tGames { get; set; }
        public virtual tRole tRole { get; set; }
        public virtual tRoute tRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameUnlock> tGameUnlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGameRecord> tGameRecords { get; set; }
    }
}
