//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tLocation()
        {
            this.tAds = new HashSet<tAd>();
            this.tAlbums = new HashSet<tAlbum>();
            this.tGames = new HashSet<tGame>();
            this.tLR_Relation = new HashSet<tLR_Relation>();
            this.tPhotoes = new HashSet<tPhoto>();
        }
    
        public int ID { get; set; }
        public string fId_Location { get; set; }
        public int fId_Role { get; set; }
        public int fId_Coordinate { get; set; }
        public int fId_ShareAuth { get; set; }
        public int fId_Icon { get; set; }
        public string fType_Location { get; set; }
        public string fName_Location { get; set; }
        public string fDescript_Location { get; set; }
        public Nullable<System.DateTime> fTime_Location { get; set; }
        public string fAdd_Location { get; set; }
        public int fDelete_Location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAd> tAds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAlbum> tAlbums { get; set; }
        public virtual tCoordinate tCoordinate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGame> tGames { get; set; }
        public virtual tIcon tIcon { get; set; }
        public virtual tShareAuth tShareAuth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLR_Relation> tLR_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPhoto> tPhotoes { get; set; }
    }
}
