//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReport
    {
        public int fId_Report { get; set; }
        public int fId_Reporter_Role { get; set; }
        public int fId_Reported_Role { get; set; }
        public Nullable<int> fId_Admin_Role { get; set; }
        public string fId_Location_Route_Comment_Photo { get; set; }
        public string fReason_Report { get; set; }
        public Nullable<System.DateTime> fTimeReport_Report { get; set; }
        public Nullable<System.DateTime> fTimeModify_Report { get; set; }
        public string fStatus_Report { get; set; }
    
        public virtual tComment tComment { get; set; }
        public virtual tLocation tLocation { get; set; }
        public virtual tPhoto tPhoto { get; set; }
        public virtual tRole tRole { get; set; }
        public virtual tRole tRole1 { get; set; }
        public virtual tRole tRole2 { get; set; }
        public virtual tRoute tRoute { get; set; }
    }
}
