//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homepage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRoute()
        {
            this.tComments = new HashSet<tComment>();
            this.tLR_Relation = new HashSet<tLR_Relation>();
            this.tReports = new HashSet<tReport>();
            this.tStatistics = new HashSet<tStatistic>();
            this.tTagMsgRelations = new HashSet<tTagMsgRelation>();
            this.tUnlocks = new HashSet<tUnlock>();
        }
    
        public int ID { get; set; }
        public string fId_Route { get; set; }
        public int fId_Role { get; set; }
        public int fId_ShareAuth { get; set; }
        public int fId_Icon { get; set; }
        public string fType_Route { get; set; }
        public string fName_Route { get; set; }
        public string fDescript_Route { get; set; }
        public Nullable<System.DateTime> fTime_Route { get; set; }
        public int fDelete_Route { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tComment> tComments { get; set; }
        public virtual tIcon tIcon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLR_Relation> tLR_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReport> tReports { get; set; }
        public virtual tRole tRole { get; set; }
        public virtual tShareAuth tShareAuth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tStatistic> tStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTagMsgRelation> tTagMsgRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUnlock> tUnlocks { get; set; }
    }
}
